#!/bin/bash
# Autoscan
# autoscan 

# This generates a file aclocal.m4 that contains macros for automake things, e.g. AM_INIT_AUTOMAKE.
aclocal -I m4/ --force
#libtoolize --force --ltdl --copy
# Check headers and creat config.h.in
autoheader -f

# Automake now reads configure.ac and the top-level Makefile.am, interprets them (e.g. see further work has to be done in some subdirectories) and, for each Makefile.am produces a Makefile.in. The argument --add-missing tells automake to provide default scripts for reporting errors, installing etc, so it can be omitted in the next runs.
automake --add-missing --copy --foreign

# Finally, let autoconf build the configure script:
autoconf
